---
server:
  port: 8989
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aarunbala/spring-cloud/
          search-paths:
          - '*mel' 
          - '*syd'
          repos:
            perf:
              pattern: 
              - '*/perf'
              uri: https://github.com/aarunbala/spring-cloud-perf/
              search-paths:
              - '*mel' 
              - '*syd'
              - '*bri'
encrypt:
  key: heloeemjk